#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDKnela")]
public partial class KnelaDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertTUsuario(TUsuario instance);
  partial void UpdateTUsuario(TUsuario instance);
  partial void DeleteTUsuario(TUsuario instance);
  partial void InsertTBoleta(TBoleta instance);
  partial void UpdateTBoleta(TBoleta instance);
  partial void DeleteTBoleta(TBoleta instance);
  partial void InsertTCliente(TCliente instance);
  partial void UpdateTCliente(TCliente instance);
  partial void DeleteTCliente(TCliente instance);
  partial void InsertTDetallePedido(TDetallePedido instance);
  partial void UpdateTDetallePedido(TDetallePedido instance);
  partial void DeleteTDetallePedido(TDetallePedido instance);
  partial void InsertTDetalleVenta(TDetalleVenta instance);
  partial void UpdateTDetalleVenta(TDetalleVenta instance);
  partial void DeleteTDetalleVenta(TDetalleVenta instance);
  partial void InsertTInsumo(TInsumo instance);
  partial void UpdateTInsumo(TInsumo instance);
  partial void DeleteTInsumo(TInsumo instance);
  partial void InsertTPedido(TPedido instance);
  partial void UpdateTPedido(TPedido instance);
  partial void DeleteTPedido(TPedido instance);
  #endregion
	
	public KnelaDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDKnelaConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public KnelaDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public KnelaDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public KnelaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public KnelaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<TUsuario> TUsuario
	{
		get
		{
			return this.GetTable<TUsuario>();
		}
	}
	
	public System.Data.Linq.Table<TBoleta> TBoleta
	{
		get
		{
			return this.GetTable<TBoleta>();
		}
	}
	
	public System.Data.Linq.Table<TCliente> TCliente
	{
		get
		{
			return this.GetTable<TCliente>();
		}
	}
	
	public System.Data.Linq.Table<TDetallePedido> TDetallePedido
	{
		get
		{
			return this.GetTable<TDetallePedido>();
		}
	}
	
	public System.Data.Linq.Table<TDetalleVenta> TDetalleVenta
	{
		get
		{
			return this.GetTable<TDetalleVenta>();
		}
	}
	
	public System.Data.Linq.Table<TInsumo> TInsumo
	{
		get
		{
			return this.GetTable<TInsumo>();
		}
	}
	
	public System.Data.Linq.Table<TPedido> TPedido
	{
		get
		{
			return this.GetTable<TPedido>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarClienteE")]
	public ISingleResult<spAgregarClienteEResult> spAgregarClienteE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="Char(4)")] string idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApellidoPaternoCliente", DbType="VarChar(50)")] string apellidoPaternoCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApellidoMaternoCliente", DbType="VarChar(50)")] string apellidoMaternoCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombresCliente", DbType="VarChar(50)")] string nombresCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dni", DbType="Int")] System.Nullable<int> dni, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(100)")] string contrasena)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCliente, apellidoPaternoCliente, apellidoMaternoCliente, nombresCliente, dni, direccion, usuario, contrasena);
		return ((ISingleResult<spAgregarClienteEResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDatosInsumo")]
	public ISingleResult<spDatosInsumoResult> spDatosInsumo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreInsumo", DbType="VarChar(50)")] string nombreInsumo)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreInsumo);
		return ((ISingleResult<spDatosInsumoResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarDetallePedidos")]
	public ISingleResult<spListarDetallePedidosResult> spListarDetallePedidos([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDetallePedido", DbType="Char(4)")] string idDetallePedido)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDetallePedido);
		return ((ISingleResult<spListarDetallePedidosResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarInsumo")]
	public ISingleResult<spAgregarInsumoResult> spAgregarInsumo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInsumo", DbType="Char(4)")] string idInsumo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoDePostre", DbType="VarChar(50)")] string tipoDePostre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreInsumo", DbType="VarChar(50)")] string nombreInsumo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescripcionInsumo", DbType="VarChar(50)")] string descripcionInsumo)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idInsumo, tipoDePostre, nombreInsumo, descripcionInsumo);
		return ((ISingleResult<spAgregarInsumoResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spElimiarInsumo")]
	public ISingleResult<spElimiarInsumoResult> spElimiarInsumo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInsumo", DbType="Char(4)")] string idInsumo)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idInsumo);
		return ((ISingleResult<spElimiarInsumoResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarInsumo")]
	public ISingleResult<spActualizarInsumoResult> spActualizarInsumo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInsumo", DbType="Char(4)")] string idInsumo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoDePostre", DbType="VarChar(50)")] string tipoDePostre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreInsumo", DbType="VarChar(50)")] string nombreInsumo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescripcionInsumo", DbType="VarChar(50)")] string descripcionInsumo)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idInsumo, tipoDePostre, nombreInsumo, descripcionInsumo);
		return ((ISingleResult<spActualizarInsumoResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarDetallePedidos")]
	public ISingleResult<spListarDetallePedidosResult1> spListarDetallePedidos1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDetallePedido", DbType="Char(4)")] string idDetallePedido)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDetallePedido);
		return ((ISingleResult<spListarDetallePedidosResult1>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarDetallePedido")]
	public ISingleResult<spAgregarDetallePedidoResult> spAgregarDetallePedido([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDetallePedido", DbType="Char(4)")] string idDetallePedido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdInsumo", DbType="Char(4)")] string idInsumo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDetalleVenta", DbType="Char(4)")] string idDetalleVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostoUnitario", DbType="Float")] System.Nullable<double> costoUnitario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CstTotal", DbType="Float")] System.Nullable<double> cstTotal)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDetallePedido, idInsumo, idDetalleVenta, costoUnitario, cantidad, cstTotal);
		return ((ISingleResult<spAgregarDetallePedidoResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spLoginUsuarioE")]
	public ISingleResult<spLoginUsuarioEResult> spLoginUsuarioE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(50)")] string contrasena)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contrasena);
		return ((ISingleResult<spLoginUsuarioEResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarContrasena1")]
	public ISingleResult<spActualizarContrasena1Result> spActualizarContrasena1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(50)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContrasenaActualizada", DbType="VarChar(50)")] string contrasenaActualizada)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contrasena, contrasenaActualizada);
		return ((ISingleResult<spActualizarContrasena1Result>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spMonto")]
	public ISingleResult<spMontoResult> spMonto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDetallePedido", DbType="Char(4)")] string idDetallePedido)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDetallePedido);
		return ((ISingleResult<spMontoResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarPedido1")]
	public ISingleResult<spAgregarPedido1Result> spAgregarPedido1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPedido", DbType="Char(4)")] string idPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdBoleta", DbType="Char(4)")] string idBoleta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fechaHora, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescripcionPedido", DbType="VarChar(50)")] string descripcionPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="Char(4)")] string idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDetallePedido", DbType="Char(4)")] string idDetallePedido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDetalleVenta", DbType="Char(4)")] string idDetalleVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descuento", DbType="Float")] System.Nullable<double> descuento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoTotal", DbType="Float")] System.Nullable<double> montoTotal)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPedido, idBoleta, fechaHora, descripcionPedido, idCliente, idDetallePedido, idDetalleVenta, descuento, montoTotal);
		return ((ISingleResult<spAgregarPedido1Result>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spVerBoleta")]
	public ISingleResult<spVerBoletaResult> spVerBoleta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDetallePedido", DbType="Char(4)")] string idDetallePedido)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDetallePedido);
		return ((ISingleResult<spVerBoletaResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spVerBoleta2")]
	public ISingleResult<spVerBoleta2Result> spVerBoleta2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDetallePedido", DbType="Char(4)")] string idDetallePedido)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDetallePedido);
		return ((ISingleResult<spVerBoleta2Result>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspListarInsumo")]
	public ISingleResult<uspListarInsumoResult> uspListarInsumo()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<uspListarInsumoResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUsuario")]
public partial class TUsuario : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Usuario;
	
	private System.Data.Linq.Binary _Contrasena;
	
	private EntitySet<TCliente> _TCliente;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContrasenaChanging(System.Data.Linq.Binary value);
    partial void OnContrasenaChanged();
    #endregion
	
	public TUsuario()
	{
		this._TCliente = new EntitySet<TCliente>(new Action<TCliente>(this.attach_TCliente), new Action<TCliente>(this.detach_TCliente));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Usuario
	{
		get
		{
			return this._Usuario;
		}
		set
		{
			if ((this._Usuario != value))
			{
				this.OnUsuarioChanging(value);
				this.SendPropertyChanging();
				this._Usuario = value;
				this.SendPropertyChanged("Usuario");
				this.OnUsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarBinary(200)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary Contrasena
	{
		get
		{
			return this._Contrasena;
		}
		set
		{
			if ((this._Contrasena != value))
			{
				this.OnContrasenaChanging(value);
				this.SendPropertyChanging();
				this._Contrasena = value;
				this.SendPropertyChanged("Contrasena");
				this.OnContrasenaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TCliente", Storage="_TCliente", ThisKey="Usuario", OtherKey="Usuario")]
	public EntitySet<TCliente> TCliente
	{
		get
		{
			return this._TCliente;
		}
		set
		{
			this._TCliente.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_TCliente(TCliente entity)
	{
		this.SendPropertyChanging();
		entity.TUsuario = this;
	}
	
	private void detach_TCliente(TCliente entity)
	{
		this.SendPropertyChanging();
		entity.TUsuario = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBoleta")]
public partial class TBoleta : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _IdBoleta;
	
	private string _IdDetalleVenta;
	
	private System.Nullable<int> _DsctoPromociones;
	
	private string _TipoDePago;
	
	private System.Nullable<int> _MontoTotal;
	
	private System.Nullable<System.DateTime> _fechaHora;
	
	private EntityRef<TDetalleVenta> _TDetalleVenta;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdBoletaChanging(string value);
    partial void OnIdBoletaChanged();
    partial void OnIdDetalleVentaChanging(string value);
    partial void OnIdDetalleVentaChanged();
    partial void OnDsctoPromocionesChanging(System.Nullable<int> value);
    partial void OnDsctoPromocionesChanged();
    partial void OnTipoDePagoChanging(string value);
    partial void OnTipoDePagoChanged();
    partial void OnMontoTotalChanging(System.Nullable<int> value);
    partial void OnMontoTotalChanged();
    partial void OnfechaHoraChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaHoraChanged();
    #endregion
	
	public TBoleta()
	{
		this._TDetalleVenta = default(EntityRef<TDetalleVenta>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBoleta", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string IdBoleta
	{
		get
		{
			return this._IdBoleta;
		}
		set
		{
			if ((this._IdBoleta != value))
			{
				this.OnIdBoletaChanging(value);
				this.SendPropertyChanging();
				this._IdBoleta = value;
				this.SendPropertyChanged("IdBoleta");
				this.OnIdBoletaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetalleVenta", DbType="Char(4) NOT NULL", CanBeNull=false)]
	public string IdDetalleVenta
	{
		get
		{
			return this._IdDetalleVenta;
		}
		set
		{
			if ((this._IdDetalleVenta != value))
			{
				if (this._TDetalleVenta.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIdDetalleVentaChanging(value);
				this.SendPropertyChanging();
				this._IdDetalleVenta = value;
				this.SendPropertyChanged("IdDetalleVenta");
				this.OnIdDetalleVentaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DsctoPromociones", DbType="Int")]
	public System.Nullable<int> DsctoPromociones
	{
		get
		{
			return this._DsctoPromociones;
		}
		set
		{
			if ((this._DsctoPromociones != value))
			{
				this.OnDsctoPromocionesChanging(value);
				this.SendPropertyChanging();
				this._DsctoPromociones = value;
				this.SendPropertyChanged("DsctoPromociones");
				this.OnDsctoPromocionesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDePago", DbType="VarChar(50)")]
	public string TipoDePago
	{
		get
		{
			return this._TipoDePago;
		}
		set
		{
			if ((this._TipoDePago != value))
			{
				this.OnTipoDePagoChanging(value);
				this.SendPropertyChanging();
				this._TipoDePago = value;
				this.SendPropertyChanged("TipoDePago");
				this.OnTipoDePagoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoTotal", DbType="Int")]
	public System.Nullable<int> MontoTotal
	{
		get
		{
			return this._MontoTotal;
		}
		set
		{
			if ((this._MontoTotal != value))
			{
				this.OnMontoTotalChanging(value);
				this.SendPropertyChanging();
				this._MontoTotal = value;
				this.SendPropertyChanged("MontoTotal");
				this.OnMontoTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaHora", DbType="DateTime")]
	public System.Nullable<System.DateTime> fechaHora
	{
		get
		{
			return this._fechaHora;
		}
		set
		{
			if ((this._fechaHora != value))
			{
				this.OnfechaHoraChanging(value);
				this.SendPropertyChanging();
				this._fechaHora = value;
				this.SendPropertyChanged("fechaHora");
				this.OnfechaHoraChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TDetalleVenta_TBoleta", Storage="_TDetalleVenta", ThisKey="IdDetalleVenta", OtherKey="IdDetalleVenta", IsForeignKey=true)]
	public TDetalleVenta TDetalleVenta
	{
		get
		{
			return this._TDetalleVenta.Entity;
		}
		set
		{
			TDetalleVenta previousValue = this._TDetalleVenta.Entity;
			if (((previousValue != value) 
						|| (this._TDetalleVenta.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TDetalleVenta.Entity = null;
					previousValue.TBoleta.Remove(this);
				}
				this._TDetalleVenta.Entity = value;
				if ((value != null))
				{
					value.TBoleta.Add(this);
					this._IdDetalleVenta = value.IdDetalleVenta;
				}
				else
				{
					this._IdDetalleVenta = default(string);
				}
				this.SendPropertyChanged("TDetalleVenta");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TCliente")]
public partial class TCliente : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _IdCliente;
	
	private string _ApellidoPaternoCliente;
	
	private string _ApellidoMaternoCliente;
	
	private string _NombresCliente;
	
	private int _Dni;
	
	private string _Direccion;
	
	private string _Usuario;
	
	private EntitySet<TPedido> _TPedido;
	
	private EntityRef<TUsuario> _TUsuario;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdClienteChanging(string value);
    partial void OnIdClienteChanged();
    partial void OnApellidoPaternoClienteChanging(string value);
    partial void OnApellidoPaternoClienteChanged();
    partial void OnApellidoMaternoClienteChanging(string value);
    partial void OnApellidoMaternoClienteChanged();
    partial void OnNombresClienteChanging(string value);
    partial void OnNombresClienteChanged();
    partial void OnDniChanging(int value);
    partial void OnDniChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    #endregion
	
	public TCliente()
	{
		this._TPedido = new EntitySet<TPedido>(new Action<TPedido>(this.attach_TPedido), new Action<TPedido>(this.detach_TPedido));
		this._TUsuario = default(EntityRef<TUsuario>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string IdCliente
	{
		get
		{
			return this._IdCliente;
		}
		set
		{
			if ((this._IdCliente != value))
			{
				this.OnIdClienteChanging(value);
				this.SendPropertyChanging();
				this._IdCliente = value;
				this.SendPropertyChanged("IdCliente");
				this.OnIdClienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoPaternoCliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string ApellidoPaternoCliente
	{
		get
		{
			return this._ApellidoPaternoCliente;
		}
		set
		{
			if ((this._ApellidoPaternoCliente != value))
			{
				this.OnApellidoPaternoClienteChanging(value);
				this.SendPropertyChanging();
				this._ApellidoPaternoCliente = value;
				this.SendPropertyChanged("ApellidoPaternoCliente");
				this.OnApellidoPaternoClienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoMaternoCliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string ApellidoMaternoCliente
	{
		get
		{
			return this._ApellidoMaternoCliente;
		}
		set
		{
			if ((this._ApellidoMaternoCliente != value))
			{
				this.OnApellidoMaternoClienteChanging(value);
				this.SendPropertyChanging();
				this._ApellidoMaternoCliente = value;
				this.SendPropertyChanged("ApellidoMaternoCliente");
				this.OnApellidoMaternoClienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombresCliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string NombresCliente
	{
		get
		{
			return this._NombresCliente;
		}
		set
		{
			if ((this._NombresCliente != value))
			{
				this.OnNombresClienteChanging(value);
				this.SendPropertyChanging();
				this._NombresCliente = value;
				this.SendPropertyChanged("NombresCliente");
				this.OnNombresClienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dni", DbType="Int NOT NULL")]
	public int Dni
	{
		get
		{
			return this._Dni;
		}
		set
		{
			if ((this._Dni != value))
			{
				this.OnDniChanging(value);
				this.SendPropertyChanging();
				this._Dni = value;
				this.SendPropertyChanged("Dni");
				this.OnDniChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Direccion
	{
		get
		{
			return this._Direccion;
		}
		set
		{
			if ((this._Direccion != value))
			{
				this.OnDireccionChanging(value);
				this.SendPropertyChanging();
				this._Direccion = value;
				this.SendPropertyChanged("Direccion");
				this.OnDireccionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Usuario
	{
		get
		{
			return this._Usuario;
		}
		set
		{
			if ((this._Usuario != value))
			{
				if (this._TUsuario.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUsuarioChanging(value);
				this.SendPropertyChanging();
				this._Usuario = value;
				this.SendPropertyChanged("Usuario");
				this.OnUsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCliente_TPedido", Storage="_TPedido", ThisKey="IdCliente", OtherKey="IdCliente")]
	public EntitySet<TPedido> TPedido
	{
		get
		{
			return this._TPedido;
		}
		set
		{
			this._TPedido.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TCliente", Storage="_TUsuario", ThisKey="Usuario", OtherKey="Usuario", IsForeignKey=true)]
	public TUsuario TUsuario
	{
		get
		{
			return this._TUsuario.Entity;
		}
		set
		{
			TUsuario previousValue = this._TUsuario.Entity;
			if (((previousValue != value) 
						|| (this._TUsuario.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TUsuario.Entity = null;
					previousValue.TCliente.Remove(this);
				}
				this._TUsuario.Entity = value;
				if ((value != null))
				{
					value.TCliente.Add(this);
					this._Usuario = value.Usuario;
				}
				else
				{
					this._Usuario = default(string);
				}
				this.SendPropertyChanged("TUsuario");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_TPedido(TPedido entity)
	{
		this.SendPropertyChanging();
		entity.TCliente = this;
	}
	
	private void detach_TPedido(TPedido entity)
	{
		this.SendPropertyChanging();
		entity.TCliente = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TDetallePedido")]
public partial class TDetallePedido : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _IdDetallePedido;
	
	private string _IdInsumo;
	
	private System.Nullable<int> _Cantidad;
	
	private System.Nullable<int> _CstUnitario;
	
	private System.Nullable<int> _CstTotal;
	
	private EntitySet<TPedido> _TPedido;
	
	private EntityRef<TInsumo> _TInsumo;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDetallePedidoChanging(string value);
    partial void OnIdDetallePedidoChanged();
    partial void OnIdInsumoChanging(string value);
    partial void OnIdInsumoChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void OnCstUnitarioChanging(System.Nullable<int> value);
    partial void OnCstUnitarioChanged();
    partial void OnCstTotalChanging(System.Nullable<int> value);
    partial void OnCstTotalChanged();
    #endregion
	
	public TDetallePedido()
	{
		this._TPedido = new EntitySet<TPedido>(new Action<TPedido>(this.attach_TPedido), new Action<TPedido>(this.detach_TPedido));
		this._TInsumo = default(EntityRef<TInsumo>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetallePedido", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string IdDetallePedido
	{
		get
		{
			return this._IdDetallePedido;
		}
		set
		{
			if ((this._IdDetallePedido != value))
			{
				this.OnIdDetallePedidoChanging(value);
				this.SendPropertyChanging();
				this._IdDetallePedido = value;
				this.SendPropertyChanged("IdDetallePedido");
				this.OnIdDetallePedidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInsumo", DbType="Char(4) NOT NULL", CanBeNull=false)]
	public string IdInsumo
	{
		get
		{
			return this._IdInsumo;
		}
		set
		{
			if ((this._IdInsumo != value))
			{
				if (this._TInsumo.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIdInsumoChanging(value);
				this.SendPropertyChanging();
				this._IdInsumo = value;
				this.SendPropertyChanged("IdInsumo");
				this.OnIdInsumoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
	public System.Nullable<int> Cantidad
	{
		get
		{
			return this._Cantidad;
		}
		set
		{
			if ((this._Cantidad != value))
			{
				this.OnCantidadChanging(value);
				this.SendPropertyChanging();
				this._Cantidad = value;
				this.SendPropertyChanged("Cantidad");
				this.OnCantidadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CstUnitario", DbType="Int")]
	public System.Nullable<int> CstUnitario
	{
		get
		{
			return this._CstUnitario;
		}
		set
		{
			if ((this._CstUnitario != value))
			{
				this.OnCstUnitarioChanging(value);
				this.SendPropertyChanging();
				this._CstUnitario = value;
				this.SendPropertyChanged("CstUnitario");
				this.OnCstUnitarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CstTotal", DbType="Int")]
	public System.Nullable<int> CstTotal
	{
		get
		{
			return this._CstTotal;
		}
		set
		{
			if ((this._CstTotal != value))
			{
				this.OnCstTotalChanging(value);
				this.SendPropertyChanging();
				this._CstTotal = value;
				this.SendPropertyChanged("CstTotal");
				this.OnCstTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TDetallePedido_TPedido", Storage="_TPedido", ThisKey="IdDetallePedido", OtherKey="IdDetallePedido")]
	public EntitySet<TPedido> TPedido
	{
		get
		{
			return this._TPedido;
		}
		set
		{
			this._TPedido.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TInsumo_TDetallePedido", Storage="_TInsumo", ThisKey="IdInsumo", OtherKey="IdInsumo", IsForeignKey=true)]
	public TInsumo TInsumo
	{
		get
		{
			return this._TInsumo.Entity;
		}
		set
		{
			TInsumo previousValue = this._TInsumo.Entity;
			if (((previousValue != value) 
						|| (this._TInsumo.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TInsumo.Entity = null;
					previousValue.TDetallePedido.Remove(this);
				}
				this._TInsumo.Entity = value;
				if ((value != null))
				{
					value.TDetallePedido.Add(this);
					this._IdInsumo = value.IdInsumo;
				}
				else
				{
					this._IdInsumo = default(string);
				}
				this.SendPropertyChanged("TInsumo");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_TPedido(TPedido entity)
	{
		this.SendPropertyChanging();
		entity.TDetallePedido = this;
	}
	
	private void detach_TPedido(TPedido entity)
	{
		this.SendPropertyChanging();
		entity.TDetallePedido = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TDetalleVenta")]
public partial class TDetalleVenta : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _IdDetalleVenta;
	
	private System.Nullable<int> _Cantidad;
	
	private string _Especificaciones;
	
	private EntitySet<TBoleta> _TBoleta;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDetalleVentaChanging(string value);
    partial void OnIdDetalleVentaChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void OnEspecificacionesChanging(string value);
    partial void OnEspecificacionesChanged();
    #endregion
	
	public TDetalleVenta()
	{
		this._TBoleta = new EntitySet<TBoleta>(new Action<TBoleta>(this.attach_TBoleta), new Action<TBoleta>(this.detach_TBoleta));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetalleVenta", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string IdDetalleVenta
	{
		get
		{
			return this._IdDetalleVenta;
		}
		set
		{
			if ((this._IdDetalleVenta != value))
			{
				this.OnIdDetalleVentaChanging(value);
				this.SendPropertyChanging();
				this._IdDetalleVenta = value;
				this.SendPropertyChanged("IdDetalleVenta");
				this.OnIdDetalleVentaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
	public System.Nullable<int> Cantidad
	{
		get
		{
			return this._Cantidad;
		}
		set
		{
			if ((this._Cantidad != value))
			{
				this.OnCantidadChanging(value);
				this.SendPropertyChanging();
				this._Cantidad = value;
				this.SendPropertyChanged("Cantidad");
				this.OnCantidadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especificaciones", DbType="VarChar(50)")]
	public string Especificaciones
	{
		get
		{
			return this._Especificaciones;
		}
		set
		{
			if ((this._Especificaciones != value))
			{
				this.OnEspecificacionesChanging(value);
				this.SendPropertyChanging();
				this._Especificaciones = value;
				this.SendPropertyChanged("Especificaciones");
				this.OnEspecificacionesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TDetalleVenta_TBoleta", Storage="_TBoleta", ThisKey="IdDetalleVenta", OtherKey="IdDetalleVenta")]
	public EntitySet<TBoleta> TBoleta
	{
		get
		{
			return this._TBoleta;
		}
		set
		{
			this._TBoleta.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_TBoleta(TBoleta entity)
	{
		this.SendPropertyChanging();
		entity.TDetalleVenta = this;
	}
	
	private void detach_TBoleta(TBoleta entity)
	{
		this.SendPropertyChanging();
		entity.TDetalleVenta = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TInsumo")]
public partial class TInsumo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _IdInsumo;
	
	private string _TipoDePostre;
	
	private string _NombreInsumo;
	
	private string _DescripcionInsumo;
	
	private EntitySet<TDetallePedido> _TDetallePedido;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdInsumoChanging(string value);
    partial void OnIdInsumoChanged();
    partial void OnTipoDePostreChanging(string value);
    partial void OnTipoDePostreChanged();
    partial void OnNombreInsumoChanging(string value);
    partial void OnNombreInsumoChanged();
    partial void OnDescripcionInsumoChanging(string value);
    partial void OnDescripcionInsumoChanged();
    #endregion
	
	public TInsumo()
	{
		this._TDetallePedido = new EntitySet<TDetallePedido>(new Action<TDetallePedido>(this.attach_TDetallePedido), new Action<TDetallePedido>(this.detach_TDetallePedido));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInsumo", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string IdInsumo
	{
		get
		{
			return this._IdInsumo;
		}
		set
		{
			if ((this._IdInsumo != value))
			{
				this.OnIdInsumoChanging(value);
				this.SendPropertyChanging();
				this._IdInsumo = value;
				this.SendPropertyChanged("IdInsumo");
				this.OnIdInsumoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDePostre", DbType="VarChar(50)")]
	public string TipoDePostre
	{
		get
		{
			return this._TipoDePostre;
		}
		set
		{
			if ((this._TipoDePostre != value))
			{
				this.OnTipoDePostreChanging(value);
				this.SendPropertyChanging();
				this._TipoDePostre = value;
				this.SendPropertyChanged("TipoDePostre");
				this.OnTipoDePostreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreInsumo", DbType="VarChar(50)")]
	public string NombreInsumo
	{
		get
		{
			return this._NombreInsumo;
		}
		set
		{
			if ((this._NombreInsumo != value))
			{
				this.OnNombreInsumoChanging(value);
				this.SendPropertyChanging();
				this._NombreInsumo = value;
				this.SendPropertyChanged("NombreInsumo");
				this.OnNombreInsumoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionInsumo", DbType="VarChar(50)")]
	public string DescripcionInsumo
	{
		get
		{
			return this._DescripcionInsumo;
		}
		set
		{
			if ((this._DescripcionInsumo != value))
			{
				this.OnDescripcionInsumoChanging(value);
				this.SendPropertyChanging();
				this._DescripcionInsumo = value;
				this.SendPropertyChanged("DescripcionInsumo");
				this.OnDescripcionInsumoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TInsumo_TDetallePedido", Storage="_TDetallePedido", ThisKey="IdInsumo", OtherKey="IdInsumo")]
	public EntitySet<TDetallePedido> TDetallePedido
	{
		get
		{
			return this._TDetallePedido;
		}
		set
		{
			this._TDetallePedido.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_TDetallePedido(TDetallePedido entity)
	{
		this.SendPropertyChanging();
		entity.TInsumo = this;
	}
	
	private void detach_TDetallePedido(TDetallePedido entity)
	{
		this.SendPropertyChanging();
		entity.TInsumo = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TPedido")]
public partial class TPedido : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _IdPedido;
	
	private System.Nullable<System.DateTime> _fechaHora;
	
	private System.Nullable<int> _NroOrdenPedido;
	
	private string _DescripcionPedido;
	
	private string _IdCliente;
	
	private string _IdDetallePedido;
	
	private EntityRef<TCliente> _TCliente;
	
	private EntityRef<TDetallePedido> _TDetallePedido;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPedidoChanging(string value);
    partial void OnIdPedidoChanged();
    partial void OnfechaHoraChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaHoraChanged();
    partial void OnNroOrdenPedidoChanging(System.Nullable<int> value);
    partial void OnNroOrdenPedidoChanged();
    partial void OnDescripcionPedidoChanging(string value);
    partial void OnDescripcionPedidoChanged();
    partial void OnIdClienteChanging(string value);
    partial void OnIdClienteChanged();
    partial void OnIdDetallePedidoChanging(string value);
    partial void OnIdDetallePedidoChanged();
    #endregion
	
	public TPedido()
	{
		this._TCliente = default(EntityRef<TCliente>);
		this._TDetallePedido = default(EntityRef<TDetallePedido>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPedido", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string IdPedido
	{
		get
		{
			return this._IdPedido;
		}
		set
		{
			if ((this._IdPedido != value))
			{
				this.OnIdPedidoChanging(value);
				this.SendPropertyChanging();
				this._IdPedido = value;
				this.SendPropertyChanged("IdPedido");
				this.OnIdPedidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaHora", DbType="DateTime")]
	public System.Nullable<System.DateTime> fechaHora
	{
		get
		{
			return this._fechaHora;
		}
		set
		{
			if ((this._fechaHora != value))
			{
				this.OnfechaHoraChanging(value);
				this.SendPropertyChanging();
				this._fechaHora = value;
				this.SendPropertyChanged("fechaHora");
				this.OnfechaHoraChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroOrdenPedido", DbType="Int")]
	public System.Nullable<int> NroOrdenPedido
	{
		get
		{
			return this._NroOrdenPedido;
		}
		set
		{
			if ((this._NroOrdenPedido != value))
			{
				this.OnNroOrdenPedidoChanging(value);
				this.SendPropertyChanging();
				this._NroOrdenPedido = value;
				this.SendPropertyChanged("NroOrdenPedido");
				this.OnNroOrdenPedidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionPedido", DbType="VarChar(50)")]
	public string DescripcionPedido
	{
		get
		{
			return this._DescripcionPedido;
		}
		set
		{
			if ((this._DescripcionPedido != value))
			{
				this.OnDescripcionPedidoChanging(value);
				this.SendPropertyChanging();
				this._DescripcionPedido = value;
				this.SendPropertyChanged("DescripcionPedido");
				this.OnDescripcionPedidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Char(4) NOT NULL", CanBeNull=false)]
	public string IdCliente
	{
		get
		{
			return this._IdCliente;
		}
		set
		{
			if ((this._IdCliente != value))
			{
				if (this._TCliente.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIdClienteChanging(value);
				this.SendPropertyChanging();
				this._IdCliente = value;
				this.SendPropertyChanged("IdCliente");
				this.OnIdClienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetallePedido", DbType="Char(4) NOT NULL", CanBeNull=false)]
	public string IdDetallePedido
	{
		get
		{
			return this._IdDetallePedido;
		}
		set
		{
			if ((this._IdDetallePedido != value))
			{
				if (this._TDetallePedido.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIdDetallePedidoChanging(value);
				this.SendPropertyChanging();
				this._IdDetallePedido = value;
				this.SendPropertyChanged("IdDetallePedido");
				this.OnIdDetallePedidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCliente_TPedido", Storage="_TCliente", ThisKey="IdCliente", OtherKey="IdCliente", IsForeignKey=true)]
	public TCliente TCliente
	{
		get
		{
			return this._TCliente.Entity;
		}
		set
		{
			TCliente previousValue = this._TCliente.Entity;
			if (((previousValue != value) 
						|| (this._TCliente.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TCliente.Entity = null;
					previousValue.TPedido.Remove(this);
				}
				this._TCliente.Entity = value;
				if ((value != null))
				{
					value.TPedido.Add(this);
					this._IdCliente = value.IdCliente;
				}
				else
				{
					this._IdCliente = default(string);
				}
				this.SendPropertyChanged("TCliente");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TDetallePedido_TPedido", Storage="_TDetallePedido", ThisKey="IdDetallePedido", OtherKey="IdDetallePedido", IsForeignKey=true)]
	public TDetallePedido TDetallePedido
	{
		get
		{
			return this._TDetallePedido.Entity;
		}
		set
		{
			TDetallePedido previousValue = this._TDetallePedido.Entity;
			if (((previousValue != value) 
						|| (this._TDetallePedido.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TDetallePedido.Entity = null;
					previousValue.TPedido.Remove(this);
				}
				this._TDetallePedido.Entity = value;
				if ((value != null))
				{
					value.TPedido.Add(this);
					this._IdDetallePedido = value.IdDetallePedido;
				}
				else
				{
					this._IdDetallePedido = default(string);
				}
				this.SendPropertyChanged("TDetallePedido");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class spAgregarClienteEResult
{
	
	private int _CodError;
	
	private string _Mensaje;
	
	public spAgregarClienteEResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
	public int CodError
	{
		get
		{
			return this._CodError;
		}
		set
		{
			if ((this._CodError != value))
			{
				this._CodError = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Mensaje
	{
		get
		{
			return this._Mensaje;
		}
		set
		{
			if ((this._Mensaje != value))
			{
				this._Mensaje = value;
			}
		}
	}
}

public partial class spDatosInsumoResult
{
	
	private string _IdInsumo;
	
	public spDatosInsumoResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInsumo", DbType="Char(4) NOT NULL", CanBeNull=false)]
	public string IdInsumo
	{
		get
		{
			return this._IdInsumo;
		}
		set
		{
			if ((this._IdInsumo != value))
			{
				this._IdInsumo = value;
			}
		}
	}
}

public partial class spListarDetallePedidosResult
{
	
	private string _IdDetallePedido;
	
	private string _IdInsumo;
	
	private System.Nullable<int> _Cantidad;
	
	private System.Nullable<int> _CstUnitario;
	
	private System.Nullable<int> _CstTotal;
	
	public spListarDetallePedidosResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetallePedido", DbType="Char(4) NOT NULL", CanBeNull=false)]
	public string IdDetallePedido
	{
		get
		{
			return this._IdDetallePedido;
		}
		set
		{
			if ((this._IdDetallePedido != value))
			{
				this._IdDetallePedido = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInsumo", DbType="Char(4) NOT NULL", CanBeNull=false)]
	public string IdInsumo
	{
		get
		{
			return this._IdInsumo;
		}
		set
		{
			if ((this._IdInsumo != value))
			{
				this._IdInsumo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
	public System.Nullable<int> Cantidad
	{
		get
		{
			return this._Cantidad;
		}
		set
		{
			if ((this._Cantidad != value))
			{
				this._Cantidad = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CstUnitario", DbType="Int")]
	public System.Nullable<int> CstUnitario
	{
		get
		{
			return this._CstUnitario;
		}
		set
		{
			if ((this._CstUnitario != value))
			{
				this._CstUnitario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CstTotal", DbType="Int")]
	public System.Nullable<int> CstTotal
	{
		get
		{
			return this._CstTotal;
		}
		set
		{
			if ((this._CstTotal != value))
			{
				this._CstTotal = value;
			}
		}
	}
}

public partial class spAgregarInsumoResult
{
	
	private int _CodError;
	
	private string _Mensaje;
	
	public spAgregarInsumoResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
	public int CodError
	{
		get
		{
			return this._CodError;
		}
		set
		{
			if ((this._CodError != value))
			{
				this._CodError = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(27) NOT NULL", CanBeNull=false)]
	public string Mensaje
	{
		get
		{
			return this._Mensaje;
		}
		set
		{
			if ((this._Mensaje != value))
			{
				this._Mensaje = value;
			}
		}
	}
}

public partial class spElimiarInsumoResult
{
	
	private int _codError;
	
	private string _Mensaje;
	
	public spElimiarInsumoResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codError", DbType="Int NOT NULL")]
	public int codError
	{
		get
		{
			return this._codError;
		}
		set
		{
			if ((this._codError != value))
			{
				this._codError = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(29) NOT NULL", CanBeNull=false)]
	public string Mensaje
	{
		get
		{
			return this._Mensaje;
		}
		set
		{
			if ((this._Mensaje != value))
			{
				this._Mensaje = value;
			}
		}
	}
}

public partial class spActualizarInsumoResult
{
	
	private int _codError;
	
	private string _Mensaje;
	
	public spActualizarInsumoResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codError", DbType="Int NOT NULL")]
	public int codError
	{
		get
		{
			return this._codError;
		}
		set
		{
			if ((this._codError != value))
			{
				this._codError = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
	public string Mensaje
	{
		get
		{
			return this._Mensaje;
		}
		set
		{
			if ((this._Mensaje != value))
			{
				this._Mensaje = value;
			}
		}
	}
}

public partial class spListarDetallePedidosResult1
{
	
	private string _IdDetallePedido;
	
	private string _IdInsumo;
	
	private System.Nullable<double> _CostoUnitario;
	
	private System.Nullable<int> _Cantidad;
	
	private System.Nullable<double> _CstTotal;
	
	public spListarDetallePedidosResult1()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetallePedido", DbType="Char(4) NOT NULL", CanBeNull=false)]
	public string IdDetallePedido
	{
		get
		{
			return this._IdDetallePedido;
		}
		set
		{
			if ((this._IdDetallePedido != value))
			{
				this._IdDetallePedido = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInsumo", DbType="Char(4) NOT NULL", CanBeNull=false)]
	public string IdInsumo
	{
		get
		{
			return this._IdInsumo;
		}
		set
		{
			if ((this._IdInsumo != value))
			{
				this._IdInsumo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoUnitario", DbType="Float")]
	public System.Nullable<double> CostoUnitario
	{
		get
		{
			return this._CostoUnitario;
		}
		set
		{
			if ((this._CostoUnitario != value))
			{
				this._CostoUnitario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
	public System.Nullable<int> Cantidad
	{
		get
		{
			return this._Cantidad;
		}
		set
		{
			if ((this._Cantidad != value))
			{
				this._Cantidad = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CstTotal", DbType="Float")]
	public System.Nullable<double> CstTotal
	{
		get
		{
			return this._CstTotal;
		}
		set
		{
			if ((this._CstTotal != value))
			{
				this._CstTotal = value;
			}
		}
	}
}

public partial class spAgregarDetallePedidoResult
{
	
	private int _CodError;
	
	private string _Mensaje;
	
	public spAgregarDetallePedidoResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
	public int CodError
	{
		get
		{
			return this._CodError;
		}
		set
		{
			if ((this._CodError != value))
			{
				this._CodError = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(53) NOT NULL", CanBeNull=false)]
	public string Mensaje
	{
		get
		{
			return this._Mensaje;
		}
		set
		{
			if ((this._Mensaje != value))
			{
				this._Mensaje = value;
			}
		}
	}
}

public partial class spLoginUsuarioEResult
{
	
	private int _CodError;
	
	private string _Mensaje;
	
	public spLoginUsuarioEResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
	public int CodError
	{
		get
		{
			return this._CodError;
		}
		set
		{
			if ((this._CodError != value))
			{
				this._CodError = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(20)")]
	public string Mensaje
	{
		get
		{
			return this._Mensaje;
		}
		set
		{
			if ((this._Mensaje != value))
			{
				this._Mensaje = value;
			}
		}
	}
}

public partial class spActualizarContrasena1Result
{
	
	private int _CodError;
	
	private string _Mensaje;
	
	public spActualizarContrasena1Result()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
	public int CodError
	{
		get
		{
			return this._CodError;
		}
		set
		{
			if ((this._CodError != value))
			{
				this._CodError = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(36) NOT NULL", CanBeNull=false)]
	public string Mensaje
	{
		get
		{
			return this._Mensaje;
		}
		set
		{
			if ((this._Mensaje != value))
			{
				this._Mensaje = value;
			}
		}
	}
}

public partial class spMontoResult
{
	
	private System.Nullable<double> _CstTotal;
	
	public spMontoResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CstTotal", DbType="Float")]
	public System.Nullable<double> CstTotal
	{
		get
		{
			return this._CstTotal;
		}
		set
		{
			if ((this._CstTotal != value))
			{
				this._CstTotal = value;
			}
		}
	}
}

public partial class spAgregarPedido1Result
{
	
	private int _CodError;
	
	private string _Mensaje;
	
	public spAgregarPedido1Result()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
	public int CodError
	{
		get
		{
			return this._CodError;
		}
		set
		{
			if ((this._CodError != value))
			{
				this._CodError = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(29) NOT NULL", CanBeNull=false)]
	public string Mensaje
	{
		get
		{
			return this._Mensaje;
		}
		set
		{
			if ((this._Mensaje != value))
			{
				this._Mensaje = value;
			}
		}
	}
}

public partial class spVerBoletaResult
{
	
	private string _IdBoleta;
	
	private System.Nullable<System.DateTime> _FechaHora;
	
	private string _NombresCliente;
	
	private string _ApellidoPaternoCliente;
	
	private string _ApellidoMaternoCliente;
	
	private string _NombreInsumo;
	
	public spVerBoletaResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBoleta", DbType="Char(4) NOT NULL", CanBeNull=false)]
	public string IdBoleta
	{
		get
		{
			return this._IdBoleta;
		}
		set
		{
			if ((this._IdBoleta != value))
			{
				this._IdBoleta = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHora", DbType="DateTime")]
	public System.Nullable<System.DateTime> FechaHora
	{
		get
		{
			return this._FechaHora;
		}
		set
		{
			if ((this._FechaHora != value))
			{
				this._FechaHora = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombresCliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string NombresCliente
	{
		get
		{
			return this._NombresCliente;
		}
		set
		{
			if ((this._NombresCliente != value))
			{
				this._NombresCliente = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoPaternoCliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string ApellidoPaternoCliente
	{
		get
		{
			return this._ApellidoPaternoCliente;
		}
		set
		{
			if ((this._ApellidoPaternoCliente != value))
			{
				this._ApellidoPaternoCliente = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoMaternoCliente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string ApellidoMaternoCliente
	{
		get
		{
			return this._ApellidoMaternoCliente;
		}
		set
		{
			if ((this._ApellidoMaternoCliente != value))
			{
				this._ApellidoMaternoCliente = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreInsumo", DbType="VarChar(50)")]
	public string NombreInsumo
	{
		get
		{
			return this._NombreInsumo;
		}
		set
		{
			if ((this._NombreInsumo != value))
			{
				this._NombreInsumo = value;
			}
		}
	}
}

public partial class spVerBoleta2Result
{
	
	private System.Nullable<double> _CostoUnitario;
	
	private System.Nullable<int> _Cantidad;
	
	private System.Nullable<double> _Descuento;
	
	private System.Nullable<double> _MontoTotal;
	
	public spVerBoleta2Result()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostoUnitario", DbType="Float")]
	public System.Nullable<double> CostoUnitario
	{
		get
		{
			return this._CostoUnitario;
		}
		set
		{
			if ((this._CostoUnitario != value))
			{
				this._CostoUnitario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
	public System.Nullable<int> Cantidad
	{
		get
		{
			return this._Cantidad;
		}
		set
		{
			if ((this._Cantidad != value))
			{
				this._Cantidad = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Float")]
	public System.Nullable<double> Descuento
	{
		get
		{
			return this._Descuento;
		}
		set
		{
			if ((this._Descuento != value))
			{
				this._Descuento = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoTotal", DbType="Float")]
	public System.Nullable<double> MontoTotal
	{
		get
		{
			return this._MontoTotal;
		}
		set
		{
			if ((this._MontoTotal != value))
			{
				this._MontoTotal = value;
			}
		}
	}
}

public partial class uspListarInsumoResult
{
	
	private string _IdInsumo;
	
	private string _TipoDePostre;
	
	private string _NombreInsumo;
	
	private string _DescripcionInsumo;
	
	public uspListarInsumoResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInsumo", DbType="Char(4) NOT NULL", CanBeNull=false)]
	public string IdInsumo
	{
		get
		{
			return this._IdInsumo;
		}
		set
		{
			if ((this._IdInsumo != value))
			{
				this._IdInsumo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDePostre", DbType="VarChar(50)")]
	public string TipoDePostre
	{
		get
		{
			return this._TipoDePostre;
		}
		set
		{
			if ((this._TipoDePostre != value))
			{
				this._TipoDePostre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreInsumo", DbType="VarChar(50)")]
	public string NombreInsumo
	{
		get
		{
			return this._NombreInsumo;
		}
		set
		{
			if ((this._NombreInsumo != value))
			{
				this._NombreInsumo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionInsumo", DbType="VarChar(50)")]
	public string DescripcionInsumo
	{
		get
		{
			return this._DescripcionInsumo;
		}
		set
		{
			if ((this._DescripcionInsumo != value))
			{
				this._DescripcionInsumo = value;
			}
		}
	}
}
#pragma warning restore 1591
